# Generated by Django 3.2 on 2022-08-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectors',
            old_name='desription',
            new_name='description',
        ),
    ]
