# Generated by Django 3.2 on 2022-08-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_rename_desription_sectors_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='sector_id',
            new_name='sector',
        ),
    ]
