# Generated by Django 3.2 on 2022-08-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_rename_sector_id_stocks_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='stock_id',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='order_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='executed_volume',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
