# Generated by Django 3.2 on 2022-08-08 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20220807_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
    ]
