# Generated by Django 3.2 on 2022-08-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_rename_user_id_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdings',
            name='bid_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='close_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='high_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='low_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ohlcv',
            name='open_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='bid_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='available_funds',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='blocked_funds',
            field=models.FloatField(),
        ),
    ]
