# Generated by Django 3.2 on 2022-08-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_auto_20220811_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='available_funds',
            field=models.FloatField(default=400000),
        ),
        migrations.AlterField(
            model_name='users',
            name='blocked_funds',
            field=models.FloatField(default=0),
        ),
    ]
